// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8g-vIbrF4ElDv8vQIAErfDiJ3q3a-Jb8',
    appId: '1:90676120528:web:e8173ea885d482153a87d5',
    messagingSenderId: '90676120528',
    projectId: 'carvia-88040',
    authDomain: 'carvia-88040.firebaseapp.com',
    storageBucket: 'carvia-88040.firebasestorage.app',
    measurementId: 'G-748VLK0MYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABQo5MpCfx3XkET2MDYdZ_pS2-JQj6u-0',
    appId: '1:90676120528:android:49cf24ea42c8970f3a87d5',
    messagingSenderId: '90676120528',
    projectId: 'carvia-88040',
    storageBucket: 'carvia-88040.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKjBWAJMh9b2gYGLoKi0-Tom9S_JWy4Hw',
    appId: '1:90676120528:ios:eaa266abf7282dbd3a87d5',
    messagingSenderId: '90676120528',
    projectId: 'carvia-88040',
    storageBucket: 'carvia-88040.firebasestorage.app',
    iosBundleId: 'com.example.carvia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKjBWAJMh9b2gYGLoKi0-Tom9S_JWy4Hw',
    appId: '1:90676120528:ios:eaa266abf7282dbd3a87d5',
    messagingSenderId: '90676120528',
    projectId: 'carvia-88040',
    storageBucket: 'carvia-88040.firebasestorage.app',
    iosBundleId: 'com.example.carvia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8g-vIbrF4ElDv8vQIAErfDiJ3q3a-Jb8',
    appId: '1:90676120528:web:cb32c97665788c8f3a87d5',
    messagingSenderId: '90676120528',
    projectId: 'carvia-88040',
    authDomain: 'carvia-88040.firebaseapp.com',
    storageBucket: 'carvia-88040.firebasestorage.app',
    measurementId: 'G-5EF4CD7V5L',
  );
}
